export const products = {
    productsList:'.features_items',
    searchInput:'[name="search"]',
    searchBtn:'#submit_search',
    resultTitel:'Searched Products',
    addToCartBtn:'.add-to-cart',
    productOverlay:'.product-overlay',
    singalProduct:'.single-products',
    continueToShopBtn:'Continue Shopping',
    tabelCart:'tr',
    viewCart:'View Cart',
    quantityDeatiel:'#quantity',
    addToCartDeatile:'Add to cart',
    cart_quantity:'.cart_quantity>button',
    features_items:'.features_items',
    addToCart:'Add to cart',
    proceedToCheckout:'Proceed To Checkout',
    registerOrLogin:"p>a[href='/login']>u",
    verfiyTitelsInDeaitels:"h2",
    placeOrder:'Place Order',
    textArea:'textarea',
    cartDeleteItem:'.cart_quantity_delete',
    leftSidebar:".left-sidebar",
    recommendedItems:'recommended items',
    addRecommendedProducts:'#recommended-item-carousel > div > div.item.active > div:nth-child(1) > div > div > div > a',
    downloadInvoiceBtn:'Download Invoice',
    downloadContinue:"[data-qa='continue-button']",
    review:{
        viewProudct:'View Product',
        titel:'Write Your Review',
        nameInput:'#name',
        emailInput:'#email',
        reviewInput:'#review',
        submitBtn:'#button-review',
        succsesMsg:'Thank you for your review.'
    },
    category:{
    categoryList:'.panel-heading',
    categoryOpenSubList:'.badge.pull-right',
    categorySubList:'.panel-body>ul',
    categorySubListOptions:'.panel-body>ul>li>a',
    confirmTextTitel:'Women - Dress Products',
    },
    brands:{
        titel:'Brands',
        brandsList:'.brands-name>ul>li>a',
    },
    paymentPage:{
        nameOfCard:"[data-qa='name-on-card']",
        cardNumber:"[data-qa='card-number']",
        cvcNumber:"[data-qa='cvc']",
        expiryMonth:"[data-qa='expiry-month']",
        expiryYear:"[data-qa='expiry-year']",
        payButton:"[data-qa='pay-button']",
        successfully:'Your order has been placed successfully!'
    },
    deatilePage:{
        category:'Category:',
        availability:'Availability:',
        condition:'Condition:',
        brand:'Brand:',
        name:'h2'
    }
}