/// <reference types="Cypress" />
import { homePage } from "../selectors/homePage";
import { signup } from "../selectors/signupPage";
import { products } from "../selectors/productsPage";
import "cypress-real-events/support";
describe('adress test',()=>{
    it('Verify address details in checkout page',()=>{
        cy.visit(homePage.path)
        cy.contains(homePage.title).should('be.visible')
        cy.get(products.features_items).scrollIntoView().should('be.visible')
        cy.get(products.singalProduct).eq(0).realHover('mouse',{force:true})
        cy.get(products.productOverlay).eq(0).should('be.visible')
        cy.contains(products.addToCart).eq(0).click({force:true})
        cy.contains(products.continueToShopBtn).click()
        cy.contains(homePage.navbarBtns.siginUpAndLoginBtn).click()
        cy.contains(signup.titel).should('be.visible')
        cy.get(signup.namkeInput).type(signup.detailesData.name)
        cy.get(signup.emailInput).type(signup.detailesData.email)
        cy.get(signup.signupBtn).click()
        cy.contains(signup.deatiles.titel).should('be.visible')
        cy.get(signup.deatiles.sexBtns).eq(0).click()
        cy.get(signup.deatiles.passwordInput).type(signup.detailesData.password)
        cy.get(signup.deatiles.daySelect).select(6)
        cy.get(signup.deatiles.monthSelect).select(4)
        cy.get(signup.deatiles.yearSelect).select(4)
        cy.contains(signup.deatiles.newsPick).click()
        cy.contains(signup.deatiles.receiveBtn).click()
        cy.get(signup.adressInfo.firstNameInput).type(signup.adressData.firstName)
        cy.get(signup.adressInfo.lastNameInput).type(signup.adressData.lastName)
        cy.get(signup.adressInfo.companyName).type(signup.adressData.company)
        cy.get(signup.adressInfo.adress).type(signup.adressData.adress)
        cy.get(signup.adressInfo.secondAdress).type(signup.adressData.adressSec)
        cy.get(signup.adressInfo.country).select(3)
        cy.get(signup.adressInfo.state).type(signup.adressData.state)
        cy.get(signup.adressInfo.city).type(signup.adressData.city)
        cy.get(signup.adressInfo.zipcode).type(signup.adressData.zipcode)
        cy.get(signup.adressInfo.mobileNumber).type(signup.adressData.mobileNumber)
        cy.get(signup.adressInfo.createBtn).click()
        cy.contains(signup.verfAcount).should('be.visible')
        cy.get(signup.continueBtn).click()
        cy.contains(signup.logedAs).should('be.visible')
        cy.contains(homePage.navbarBtns.cartBtn).click()
        cy.contains(products.proceedToCheckout).should('be.visible')
        cy.contains(products.proceedToCheckout).click()
        cy.contains('Mr. '+signup.adressData.firstName+' '+signup.adressData.lastName).should('be.visible')
        cy.contains(signup.adressData.company).should('be.visible')
        cy.contains(signup.adressData.adress).should('be.visible')
        cy.contains(signup.adressData.adressSec).should('be.visible')
        cy.contains(signup.adressData.city+' '+signup.adressData.state+' '+signup.adressData.zipcode).should('be.visible')
        cy.contains(signup.adressData.country).should('be.visible')
        cy.contains(signup.adressData.mobileNumber).should('be.visible')
        cy.get(products.textArea).type("hcbvhfdvbbv") 
        cy.contains(products.placeOrder).click()
        cy.get(products.paymentPage.nameOfCard).type("12343")
        cy.get(products.paymentPage.cardNumber).type("1234")
        cy.get(products.paymentPage.cvcNumber).type("311")
        cy.get(products.paymentPage.expiryMonth).type("04")
        cy.get(products.paymentPage.expiryYear).type("2027")
        cy.get(products.paymentPage.payButton).click()
        cy.readFile("C:/Users/DELL/Desktop/cypressAutomation/cypress/downloads/invoice.txt").should('contain','Hi mordi hanzin, Your total purchase amount is 0. Thank you')
        cy.contains(products.downloadInvoiceBtn).should('be.visible').click()
        cy.downloadFile('C:/Users/DELL/Downloads/invoice.txt','cypress/dowbloads')
        cy.readFile("C:/Users/DELL/Desktop/cypressAutomation/cypress/downloads/invoice.txt").should('contain','Hi mordi hanzin, Your total purchase amount is 0. Thank you')
        cy.get(products.downloadContinue).click()
        cy.contains(signup.deleteBtn).click()
        cy.contains(signup.verfDelete).should('be.visible')
        cy.get(signup.continueDeleteBtn).click()
    })
})