import { homePage } from "../selectors/homePage";
import { products } from "../selectors/productsPage";
import { loginPage } from "../selectors/loginPage";
import "cypress-real-events/support";
describe('product tests',()=>{
    it('Verify All Products and product detail page',()=>{
        cy.visit(homePage.path)
        cy.contains(homePage.title).should('be.visible')
        cy.contains(homePage.navbarBtns.productsBtn).click()
        cy.url().should('include', '/products')
        cy.get(products.productsList).should('be.visible')
        cy.contains(products.viewProudct).click()
        cy.get(products.deatilePage.name).should('be.visible')
        cy.contains(products.deatilePage.availability).should('be.visible')
        cy.contains(products.deatilePage.brand).should('be.visible')
        cy.contains(products.deatilePage.category).should('be.visible')
        cy.contains(products.deatilePage.condition).should('be.visible')
})
    it('verfiy add',()=>{
        cy.visit(homePage.path)
        cy.contains(homePage.title).should('be.visible')
        cy.contains(homePage.navbarBtns.productsBtn).click()
        cy.url().should('include', '/products')
        cy.get(products.productsList).should('be.visible')
        cy.get(products.singalProduct).eq(0).realHover('mouse')
        cy.get(products.productOverlay).eq(0).should('be.visible')
        cy.get(products.addToCartBtn).eq(0).click()
        cy.contains(products.continueToShopBtn).click()
        cy.get(products.singalProduct).eq(1).realHover('mouse')
        cy.get(products.productOverlay).eq(1).should('be.visible')
        cy.get(products.addToCartBtn).eq(2).click()
        cy.contains(products.viewCart).click()
        cy.get(products.tabelCart).should('have.length', 3)


})

it('verfiy quantity add ',()=>{
    cy.visit(homePage.path)
    cy.contains(homePage.title).should('be.visible')
    cy.contains(homePage.navbarBtns.productsBtn).click()
    cy.url().should('include', '/products')
    cy.get(products.productsList).should('be.visible')
    cy.contains(products.viewProudct).click()
    cy.get(products.deatilePage.name).should('be.visible')
    cy.contains(products.deatilePage.availability).should('be.visible')
    cy.contains(products.deatilePage.brand).should('be.visible')
    cy.contains(products.deatilePage.category).should('be.visible')
    cy.contains(products.deatilePage.condition).should('be.visible')
    cy.get(products.quantityDeatiel).invoke('val',4)
    cy.contains(products.addToCartDeatile).click()
    cy.contains(products.viewCart).click()
    cy.get(products.cart_quantity).should('have.text','4')
})

it('Remove Products From Cart',()=>{
    cy.visit(homePage.path)
    cy.contains(homePage.title).should('be.visible')
    cy.contains(homePage.navbarBtns.productsBtn).click()
    cy.url().should('include', '/products')
    cy.get(products.productsList).should('be.visible')
    cy.get(products.singalProduct).eq(0).realHover('mouse')
    cy.get(products.productOverlay).eq(0).should('be.visible')
    cy.get(products.addToCartBtn).eq(0).click()
    cy.contains(products.continueToShopBtn).click()
    cy.contains(homePage.navbarBtns.cartBtn).click()
    cy.get(products.tabelCart).should('have.length',2)
    cy.get(products.cart_quantity).eq(0).should('have.text','1')
    cy.get(products.cartDeleteItem).eq(0).click();
    cy.get(products.tabelCart).should('not.be.visible')

})

it('verfiy search',()=>{
    cy.visit(homePage.path)
    cy.contains(homePage.title).should('be.visible')
    cy.contains(homePage.navbarBtns.productsBtn).click()
    cy.url().should('include', '/products')
   cy.get(products.searchInput).type("Blue Top")
   cy.get(products.searchBtn).click()
   cy.contains(products.resultTitel).should('be.visible')
   cy.contains("Blue Top").should('be.visible')
})

it('Search Products and Verify Cart After Login',()=>{
    cy.visit(homePage.path)
    cy.contains(homePage.title).should('be.visible')
    cy.contains(homePage.navbarBtns.productsBtn).click()
    cy.url().should('include', '/products')
   cy.get(products.searchInput).type("Blue Top")
   cy.get(products.searchBtn).click()
   cy.contains(products.resultTitel).should('be.visible')
   cy.contains("Blue Top").should('be.visible')
   cy.get(products.productsList).should('be.visible')
   cy.get(products.singalProduct).eq(0).realHover('mouse')
   cy.get(products.productOverlay).eq(0).should('be.visible')
   cy.get(products.addToCartBtn).eq(0).click()
   cy.contains(products.continueToShopBtn).click()
   cy.contains(homePage.navbarBtns.cartBtn).click()
   cy.get(products.tabelCart).should('have.length',2)
   cy.contains(homePage.navbarBtns.siginUpAndLoginBtn).click()
   cy.contains(loginPage.title).should('be.visible')
   cy.get(loginPage.emailInput).type(loginPage.detailesData.email)
   cy.get(loginPage.passwordInput).type(loginPage.detailesData.password)
   cy.get(loginPage.loginBtn).click()
   cy.contains(loginPage.logedAs).should('be.visible')
   cy.contains(homePage.navbarBtns.cartBtn).click()
   cy.get(products.tabelCart).should('have.length',2)
   
})
it(' Add review on product',()=>{
    cy.visit(homePage.path)
    cy.contains(homePage.title).should('be.visible')
    cy.contains(homePage.navbarBtns.productsBtn).click()
    cy.url().should('include', '/products')
    cy.contains(products.review.viewProudct).eq(0).click()
    cy.url().should('include', '/product_details')
    cy.contains(products.review.titel).should('be.visible').scrollIntoView()
    cy.get(products.review.nameInput).should('be.visible').type('motty')
    cy.get(products.review.emailInput).type('mottyhn13@gmail.com')
    cy.get(products.review.reviewInput).type('iuhydjshy gfujgvc')
    cy.get(products.review.submitBtn).click()
    cy.contains(products.review.succsesMsg).should('be.visible')
})
it.only('Add to cart from Recommended items',()=>{
    cy.visit(homePage.path)
    cy.contains(homePage.title).should('be.visible')
    cy.scrollTo("bottom")
    cy.contains(products.recommendedItems).should('be.visible')
    cy.get(products.addRecommendedProducts).eq(0).click()
    cy.contains(products.viewCart).click()
    cy.get(products.tabelCart).should('be.visible').should('have.length',2)
})
})